/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author nwjsh
 */
public class addcourse extends javax.swing.JFrame {

    /**
     * Creates new form addcourse
     */
    public addcourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Course_Name = new javax.swing.JTextField();
        Course_Code = new javax.swing.JTextField();
        Course_description = new javax.swing.JScrollPane();
        Course_Description = new javax.swing.JTextArea();
        Course_Duration = new javax.swing.JTextField();
        submit_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        blurr = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 649));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADD NEW COURSE");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 0, 340, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 440, 70);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 50, 370, 540);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setText("Course Description :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 340, 160, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setText("Course Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 130, 110, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Course Code :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 200, 110, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("Course Duration :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 270, 130, 30);

        Course_Name.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        Course_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Course_Name);
        Course_Name.setBounds(120, 160, 230, 40);

        Course_Code.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        Course_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_CodeActionPerformed(evt);
            }
        });
        getContentPane().add(Course_Code);
        Course_Code.setBounds(120, 230, 230, 40);

        Course_Description.setColumns(20);
        Course_Description.setRows(5);
        Course_description.setViewportView(Course_Description);

        getContentPane().add(Course_description);
        Course_description.setBounds(120, 370, 234, 130);

        Course_Duration.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        Course_Duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_DurationActionPerformed(evt);
            }
        });
        getContentPane().add(Course_Duration);
        Course_Duration.setBounds(120, 300, 230, 40);

        submit_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submit_btn.setText("Add Course");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(submit_btn);
        submit_btn.setBounds(320, 550, 110, 50);

        Back_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back_btn.setText("Back");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Back_btn);
        Back_btn.setBounds(60, 550, 80, 50);

        blurr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bgblur.png"))); // NOI18N
        blurr.setText("jLabel2");
        getContentPane().add(blurr);
        blurr.setBounds(20, 20, 440, 610);

        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resizebg.png"))); // NOI18N
        getContentPane().add(bgimg);
        bgimg.setBounds(0, -11, 1000, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Course_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Course_NameActionPerformed

    private void Course_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Course_CodeActionPerformed

    private void Course_DurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_DurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Course_DurationActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        String Course_Name = Course_Name.getText();
        String Course_Code = Course_Code.getText():
        String Course_Duration = Course_Duration.getText();
        String Course_Description = Course_description.getText();
    }//GEN-LAST:event_submit_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JTextField Course_Code;
    private javax.swing.JTextArea Course_Description;
    private javax.swing.JTextField Course_Duration;
    private javax.swing.JTextField Course_Name;
    private javax.swing.JScrollPane Course_description;
    private javax.swing.JLabel bgimg;
    private javax.swing.JLabel blurr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
