/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nwjsh
 */
public class admin_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin_dashboard
     */
    public admin_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_btn = new javax.swing.JButton();
        routine_btn = new javax.swing.JButton();
        notice_btn = new javax.swing.JButton();
        quiz_btn = new javax.swing.JButton();
        attandance_btn = new javax.swing.JButton();
        calender_btn = new javax.swing.JButton();
        profile_btn = new javax.swing.JButton();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1512, 982));
        setMinimumSize(new java.awt.Dimension(1512, 982));
        setPreferredSize(new java.awt.Dimension(1512, 982));
        setSize(new java.awt.Dimension(1512, 982));
        getContentPane().setLayout(null);

        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bglogo.png"))); // NOI18N
        home_btn.setBorder(null);
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        getContentPane().add(home_btn);
        home_btn.setBounds(20, 20, 320, 70);

        routine_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        routine_btn.setText("Routine");
        routine_btn.setBorder(null);
        getContentPane().add(routine_btn);
        routine_btn.setBounds(410, 40, 75, 30);

        notice_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        notice_btn.setText("Notices");
        notice_btn.setBorder(null);
        notice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notice_btnActionPerformed(evt);
            }
        });
        getContentPane().add(notice_btn);
        notice_btn.setBounds(550, 40, 75, 30);

        quiz_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        quiz_btn.setText("Quiz");
        quiz_btn.setBorder(null);
        quiz_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_btnActionPerformed(evt);
            }
        });
        getContentPane().add(quiz_btn);
        quiz_btn.setBounds(690, 40, 75, 30);

        attandance_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        attandance_btn.setText("Attandance");
        attandance_btn.setBorder(null);
        attandance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attandance_btnActionPerformed(evt);
            }
        });
        getContentPane().add(attandance_btn);
        attandance_btn.setBounds(980, 40, 100, 30);

        calender_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        calender_btn.setText("Calender");
        calender_btn.setBorder(null);
        getContentPane().add(calender_btn);
        calender_btn.setBounds(840, 40, 80, 30);

        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profil.png"))); // NOI18N
        profile_btn.setBorder(null);
        getContentPane().add(profile_btn);
        profile_btn.setBounds(1420, 20, 70, 70);

        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg image.png"))); // NOI18N
        getContentPane().add(bgimg);
        bgimg.setBounds(0, 0, 1510, 982);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_btnActionPerformed

    private void attandance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attandance_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attandance_btnActionPerformed

    private void notice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notice_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notice_btnActionPerformed

    private void quiz_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quiz_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attandance_btn;
    private javax.swing.JLabel bgimg;
    private javax.swing.JButton calender_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton notice_btn;
    private javax.swing.JButton profile_btn;
    private javax.swing.JButton quiz_btn;
    private javax.swing.JButton routine_btn;
    // End of variables declaration//GEN-END:variables
}
