/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import javax.swing.*;

import controller.StudentController;
import Model.Student;
import com.sun.jdi.connect.spi.Connection;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;

/**
 *
 * @author Lenovo
 */
public class SignUpJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpJFrame
     */
    public SignUpJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu3 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        f_name1 = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        femail = new javax.swing.JLabel();
        parents_name1 = new javax.swing.JTextField();
        g_name = new javax.swing.JLabel();
        password01 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        dateofbirth = new javax.swing.JLabel();
        dob1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        gender = new javax.swing.JLabel();
        others = new javax.swing.JRadioButton();
        l_name1 = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        std_contact1 = new javax.swing.JTextField();
        parent_contact1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JLabel();
        ConfirmPass1 = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        security_ans1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jMenu3.setText("jMenu3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(134, 204, 252));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 650));
        jPanel1.setLayout(null);

        f_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        jPanel1.add(f_name1);
        f_name1.setBounds(140, 120, 240, 40);

        firstname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstname.setText("First Name:");
        jPanel1.add(firstname);
        firstname.setBounds(140, 100, 80, 17);

        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        jPanel1.add(email1);
        email1.setBounds(140, 190, 240, 40);

        femail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        femail.setText("Email address:");
        jPanel1.add(femail);
        femail.setBounds(140, 170, 90, 17);

        parents_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parents_name1ActionPerformed(evt);
            }
        });
        jPanel1.add(parents_name1);
        parents_name1.setBounds(140, 260, 240, 40);

        g_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        g_name.setText("Guardian's Full Name:");
        jPanel1.add(g_name);
        g_name.setBounds(140, 240, 160, 17);

        password01.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password01.setText("Password:");
        jPanel1.add(password01);
        password01.setBounds(140, 310, 70, 17);

        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        jPanel1.add(password1);
        password1.setBounds(140, 330, 240, 40);

        dateofbirth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateofbirth.setText("Date of Birth:");
        jPanel1.add(dateofbirth);
        dateofbirth.setBounds(140, 390, 120, 17);

        dob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob1ActionPerformed(evt);
            }
        });
        jPanel1.add(dob1);
        dob1.setBounds(140, 410, 240, 40);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel3.setLayout(null);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female);
        female.setBounds(0, 40, 70, 22);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel3.add(male);
        male.setBounds(0, 20, 60, 22);

        gender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gender.setText("Gender:");
        jPanel3.add(gender);
        gender.setBounds(10, 0, 60, 17);

        buttonGroup1.add(others);
        others.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        others.setText("Other");
        others.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        jPanel3.add(others);
        others.setBounds(0, 60, 70, 21);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(140, 460, 100, 90);

        l_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_name1ActionPerformed(evt);
            }
        });
        jPanel1.add(l_name1);
        l_name1.setBounds(590, 120, 250, 40);

        lastname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastname.setText("Last Name:");
        jPanel1.add(lastname);
        lastname.setBounds(590, 100, 100, 17);

        contact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contact.setText("Contact no:");
        jPanel1.add(contact);
        contact.setBounds(590, 170, 80, 20);

        std_contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_contact1ActionPerformed(evt);
            }
        });
        jPanel1.add(std_contact1);
        std_contact1.setBounds(590, 190, 250, 40);

        parent_contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent_contact1ActionPerformed(evt);
            }
        });
        jPanel1.add(parent_contact1);
        parent_contact1.setBounds(590, 260, 250, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Guardian's Contact no:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(590, 240, 160, 17);

        confirmpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        confirmpassword.setText("Confirm password:");
        jPanel1.add(confirmpassword);
        confirmpassword.setBounds(590, 310, 130, 17);

        ConfirmPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPass1);
        ConfirmPass1.setBounds(590, 330, 250, 40);

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckBox2.setText("View Password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(740, 370, 110, 19);

        jPanel5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Security Question:");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("What is your favourite colour?");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 26, 200, 17);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(590, 400, 250, 50);

        security_ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_ans1ActionPerformed(evt);
            }
        });
        jPanel1.add(security_ans1);
        security_ans1.setBounds(640, 460, 200, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Ans:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(590, 460, 40, 0);

        signupbtn.setBackground(new java.awt.Color(0, 0, 0));
        signupbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(255, 255, 255));
        signupbtn.setText("SIGN UP");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbtn);
        signupbtn.setBounds(590, 520, 110, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 520, 100, 50);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CREATE A NEW ACCOUNT");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(190, 0, 510, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(70, 30, 870, 60);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckBox1.setText("View Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(280, 370, 110, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/transparent.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 30, 870, 570);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 190, 170, 140);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setText("UNIVERSITAS");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 280, 220, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resizebg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -20, 1000, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void security_ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_ans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_security_ans1ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        String f_name = f_name1.getText();
        String l_name = l_name1.getText();
        String email = email1.getText();
        String std_contact = std_contact1.getText();
        String parents_name = parents_name1.getText();
        String parent_contact = parent_contact1.getText();
        String password = new String(password1.getPassword());
        String C_pass = new String(ConfirmPass1.getPassword());
        String dob = dob1.getText();
        String security_ans = security_ans1.getText();
        String gender = "";
        
        if (f_name1.getText().isEmpty() || l_name1.getText().isEmpty() || email1.getText().isEmpty() || password1.getText().isEmpty() || ConfirmPass1.getText().isEmpty() || std_contact1.getText().isEmpty() || parent_contact1.getText().isEmpty() || parents_name1.getText().isEmpty() || dob1.getText().isEmpty() || security_ans1.getText().toString().equals("None")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"One of the required field is empty", "ERROR",JOptionPane.ERROR_MESSAGE);
        } else if(!password.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
            JOptionPane.showMessageDialog(null,"Invalid password, Use  8 characters which contains atleast 1 uppercase letter, One lowecase letter, a symbol and a number", "ERROR",JOptionPane.ERROR_MESSAGE);
        } else if (!password.equals(C_pass)) {
            JOptionPane.showMessageDialog(null,"Password and Confirm Password should be same", "ERROR",JOptionPane.ERROR_MESSAGE);
        } else {   
            if (male.isSelected()) {
                gender = "Male";
            } else if (female.isSelected()) {
                gender = "Female";
            } else if (others.isSelected()) {
                gender = "others";
            }
            try {
                Student s1 = new Student(f_name, l_name,  std_contact,email, parents_name,dob, parent_contact, password,  gender,security_ans );
                StudentController sc  = new StudentController();
                int result = sc.insertdetails(s1);
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Signup Successfull");
                    dispose();
                    new login().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Error Occured during Signup");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Error Occured during Signup: " + e.getMessage());}
    }

//        if (f_name1.getText().isEmpty()|l_name1.getText().isEmpty()|email1.getText().isEmpty()|password1.getText().isEmpty()|ConfirmPass1.getText().isEmpty()|std_contact1.getText().isEmpty()|parent_contact1.getText().isEmpty()|parents_name1.getText().isEmpty()|dob1.getText().isEmpty()|security_ans1.getSelectedText().equals("None")){
//            getToolkit().beep();
//            JOptionPane.showMessageDialog(null,"One of the required field is empty", "ERROR",JOptionPane.ERROR_MESSAGE,null);
//        }
//  
//        
//        else if(!(password1.getText().trim().matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")))
//        {
//        JOptionPane.showMessageDialog(null,"Invalid password, Use  8 characters which contains atleast 1 uppercase letter, One lowecase letter, a symbol and a number", "ERROR",JOptionPane.ERROR_MESSAGE,null);
//        }
//        else{   
//        try {
//            Student s1 = new Student(f_name1, l_name1, email1, std_contact1, parents_name1, parent_contact1, password1, ConfirmPass1,dob1,security_ans1);
//            StudentController sc  = new StudentController();
//            int result = sc.insertdetails(s1);
//            pst.setString(1, f_name1.getText());
//            pst.setString(2, l_name1.getText());
//            pst.setString(3, parent_contact1.getText());
//            pst.setString(4, .getSelectedItem().toString());
//            if (male.isSelected()) {
//           gender="Male";
//           }if (female.isSelected()) {
//           gender="Female";
//       }
//       if (others.isSelected()) {
//        gender="others";
//       }
//    
//       pst.setString(6, gender);
//       
//            pst.setString(7, dob1.getText());
//            pst.setString(8, std_contact.getText());
//            pst.setString(9, email.getText());
//            
//            pst.executeUpdate();
//            
//            System.out.println("1");
//            
//            if(password.getText().equals(confirmpassword.getText())){
//            String query1 = "INSERT INTO student (usertype,username,password) values(?,?,?)";
//            PreparedStatement pst1 = con.prepareStatement(query1);
//            pst1.setString(1, "Manager");
//            pst1.setString(2, f_name1.getText());
//            pst1.setString(3, password.getText());
//            
//            System.out.println("2");
//           
// 
//                        pst1.executeUpdate();
//          
//          
//                        
//                        System.out.println("3");
//                
//            
//            JOptionPane.showMessageDialog(null, "Signup Successfull");
//            
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "Password Confirmation Does not match");
//            }
//            
//            
//          
//
//        } catch (Exception e) {
//           JOptionPane.showMessageDialog(null, e);
//            
//        }

//        String gender = null;
//        if (male.isSelected()) {
//            gender = "male";
//        } else if (female.isSelected()) {
//            gender = "female";
//        } else {
//            gender = "others";
//        }
//
//        // Validate user input
//        if (f_name.isEmpty() || l_name.isEmpty() || email.isEmpty() || std_contact.isEmpty() || parents_name.isEmpty() || parent_contact.isEmpty() || password.isEmpty() || C_pass.isEmpty() || dob.isEmpty() || security_ans.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please fill in all fields");
//            return;
//        }
//
//        if (!password.equals(C_pass)) {
//            JOptionPane.showMessageDialog(this, "Passwords do not match");
//            return;
//        }}
            // TODO add your handling code here:
    }//GEN-LAST:event_signupbtnActionPerformed

    private void parents_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parents_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parents_name1ActionPerformed

    private void l_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_name1ActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    private void parent_contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parent_contact1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void dob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected()){
            ConfirmPass1.setEchoChar((char)0);
        }
        else{
            ConfirmPass1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            password1.setEchoChar((char)0);
        }
        else{
            password1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
        new login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void std_contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_contact1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPass1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel confirmpassword;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JTextField dob1;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField f_name1;
    private javax.swing.JLabel femail;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel g_name;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JTextField l_name1;
    private javax.swing.JLabel lastname;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton others;
    private javax.swing.JTextField parent_contact1;
    private javax.swing.JTextField parents_name1;
    private javax.swing.JLabel password01;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField security_ans1;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField std_contact1;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
