package view;

import javax.swing.*;
import controller.StudentController;
import Model.Student;

public class Userlogin extends javax.swing.JFrame {


    public Userlogin() {
        initComponents();
        try{
            name.setEditable(false);
            date_of_birth.setEditable(false);
            gurdian_name.setEditable(false);
            gurdian_contact.setEditable(false);
            contact_no.setEditable(false);
            email.setEditable(false);
            gurdian_contact.setEditable(false);
        }catch(
            Exception e){
                e.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        student_information = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        date_of_birth = new javax.swing.JTextField();
        gurdian_contact = new javax.swing.JTextField();
        contact_no = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        gurdian_name = new javax.swing.JTextField();
        gurdian_no = new javax.swing.JLabel();
        gurdian = new javax.swing.JLabel();
        no_lbl = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        main = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        transparent_img = new javax.swing.JLabel();
        bg_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 649));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        student_information.setBackground(new java.awt.Color(0, 0, 0));
        student_information.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        student_information.setForeground(new java.awt.Color(255, 255, 255));
        student_information.setText("STUDENT INFROMATION");
        jPanel1.add(student_information);
        student_information.setBounds(240, 0, 390, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 60, 830, 60);

        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back_btn.setText("Back");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(0, 0, 70, 30);

        delete_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete_btn.setText("Delete Account");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(720, 480, 124, 30);

        date_of_birth.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        date_of_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_of_birthActionPerformed(evt);
            }
        });
        getContentPane().add(date_of_birth);
        date_of_birth.setBounds(250, 400, 150, 30);

        gurdian_contact.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        gurdian_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gurdian_contactActionPerformed(evt);
            }
        });
        getContentPane().add(gurdian_contact);
        gurdian_contact.setBounds(680, 350, 170, 30);

        contact_no.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        getContentPane().add(contact_no);
        contact_no.setBounds(250, 250, 150, 30);

        email.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        getContentPane().add(email);
        email.setBounds(250, 320, 150, 30);

        name.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(250, 180, 150, 30);

        gurdian_name.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        gurdian_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gurdian_nameActionPerformed(evt);
            }
        });
        getContentPane().add(gurdian_name);
        gurdian_name.setBounds(680, 230, 170, 30);

        gurdian_no.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        gurdian_no.setText("Gurdian Number :");
        getContentPane().add(gurdian_no);
        gurdian_no.setBounds(530, 350, 150, 30);

        gurdian.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        gurdian.setText("Gurdian Name :");
        getContentPane().add(gurdian);
        gurdian.setBounds(530, 230, 150, 30);

        no_lbl.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        no_lbl.setText("Contact no :");
        getContentPane().add(no_lbl);
        no_lbl.setBounds(140, 250, 110, 30);

        dob.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        dob.setText("Date of birth:");
        getContentPane().add(dob);
        dob.setBounds(140, 400, 110, 30);

        main.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        main.setText("E-mail :");
        getContentPane().add(main);
        main.setBounds(140, 320, 110, 30);

        name_lbl.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        name_lbl.setText("Name :");
        getContentPane().add(name_lbl);
        name_lbl.setBounds(140, 180, 110, 30);

        transparent_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/transparent.png"))); // NOI18N
        getContentPane().add(transparent_img);
        transparent_img.setBounds(80, 40, 830, 530);

        bg_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/resizebg.png"))); // NOI18N
        getContentPane().add(bg_img);
        bg_img.setBounds(0, 0, 1000, 649);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void date_of_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_of_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_of_birthActionPerformed

    private void gurdian_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gurdian_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gurdian_contactActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void gurdian_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gurdian_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gurdian_nameActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        dispose();
        new stddshbrd().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        JFrame frame=new JFrame("DELETE ACCOUNT");
       
      if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to DELETE your account?","DELETE ACCOUNT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
      {
           System.exit(0);
      }
// TODO add your handling code here:
    }//GEN-LAST:event_delete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Userlogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg_img;
    private javax.swing.JTextField contact_no;
    private javax.swing.JTextField date_of_birth;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField email;
    private javax.swing.JLabel gurdian;
    private javax.swing.JTextField gurdian_contact;
    private javax.swing.JTextField gurdian_name;
    private javax.swing.JLabel gurdian_no;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel main;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel no_lbl;
    private javax.swing.JLabel student_information;
    private javax.swing.JLabel transparent_img;
    // End of variables declaration//GEN-END:variables
}
